disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sourish Sarkar"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   #logo = "assets/profile.jpg"
   #secondaryLogo = "assets/profile.jpg"
   description = "My personal website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Sourish Sarkar"
  email = "sourish.sarkar13@gmail.com"
   image = "profile.jpg"
   imageQuality = 96
  headline = "Pursuing MS at Indian Statistical Institute"
#   bio = "A little bit about you"
   links = [
     { email = "sourish.sarkar13@gmail.com" },
     { instagram = "https://www.instagram.com/sourishsar/" },
      { linkedin = "https://linkedin.com/in/sourish-sarkar" },
#     { orcid = "https://orcid.org/userid" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
     { whatsapp = "https://wa.me/8777260944" },
  ]
